#!/bin/bash

[ -e /etc/default/@@PKG@@ ] && rm /etc/default/@@PKG@@
echo "export PATH=\$PATH:/usr/bin" > /etc/default/@@PKG@@;
echo "export PYTHONPATH=@@PKG_ROOT@@/lib/python@@PYTHON_VERSION_MAIN@@/site-packages" >> /etc/default/@@PKG@@;
echo "export POLARIS_INSTALL_PREFIX=@@PKG_ROOT@@" >> /etc/default/@@PKG@@;

chmod 755 @@PKG_ROOT@@/lib/python@@PYTHON_VERSION_MAIN@@
chmod 755 @@PKG_ROOT@@/lib/python@@PYTHON_VERSION_MAIN@@/site-packages

[ ! -f @@INIT_SHARE_SCRIPT@@ ] || @@INIT_SHARE_SCRIPT@@ postinst
